version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django:
    image: vt2.fsdev.io/alted/django:${VERSION}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file: .env.production
    command: /gunicorn.sh
    ports:
      - "5000:5000"

  postgres:
    image: vt2.fsdev.io/alted/postgres:${VERSION}
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backupss
    env_file: .env.production

  redis:
    image: redis:3.0

  celeryworker:
    image: vt2.fsdev.io/alted/celeryworker:${VERSION}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    env_file: .env.production
    depends_on:
     - postgres
     - redis
    command: /start-celeryworker.sh

  celerybeat:
    image: vt2.fsdev.io/alted/celerybeat:${VERSION}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    env_file: .env.production
    depends_on:
      - postgres
      - redis
    command: /start-celerybeat.sh

